CITIZEN_COLLECTION_NAME = 'citizens'
LANDMARK_COLLECTION_NAME = 'landmarks'
ADMIN_COLLECTION_NAME = 'admins'
VACCINE_COLLECTION_NAME = 'vaccines'
AREA_COLLECTION_NAME = 'areas'


SECOND_IN_YEAR = 31536000
SECOND_IN_MONTH = 2629800
SECOND_IN_WEEK = 604800
SECOND_IN_DAY = 86400

DAY_UNIT = 'day'
WEEK_UNIT = 'week'
MONTH_UNIT = 'month'
YEAR_UNIT = 'year'
ALL_UNIT = 'all'

HOUR_IN_DAY = 24
DAY_IN_DAY = 1
DAY_IN_WEEK = 7
DAY_IN_MONTH = 30
DAY_IN_YEAR = 365

OLDEST = '$min'
YOUNGEST = '$max'